res = []
res = [Print]
res = [Print; Asterisque]
res = [Print; Asterisque; Virgule]
res = [Print; Asterisque; Virgule; Chaine "\"Hello World\""]
res = [Print; Print]
res = [Print; Print; Chaine "\"Hello World\""]